workflows:
  default:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
    steps:
      - checkout

      - run: |
          nvm install 16
          nvm use 16
          npm install

      - run: |
          npx cap sync android
          npx cap open android
          cd android
          ./gradlew assembleRelease

      - deploy: android/app/build/outputs/apk/release/app-release.apk
