workflows:
  default:
    name: Build React + Capacitor Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
      node: latest
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: 检出代码
        script: |
          git checkout .

      - name: 安装依赖
        script: |
          npm ci

      - name: 构建 Web 应用
        script: |
          npm run build

      - name: 安装 Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: 检查并添加 Android 平台
        script: |
          if [ ! -d "android" ]; then
            echo "Adding Android platform..."
            npx cap add android
          else
            echo "Android platform already exists."
          fi

      - name: 同步资源
        script: |
          npx cap copy android

      - name: 构建 APK
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk

    publishing:
      email:
        recipients:
          - dev@yourcompany.com
        notify:
          success: true
          failure: true
