workflows:
  android:
    name: Build Android APK
    instance_type: mac_mini_m1
    scripts:
      - name: Clean Gradle cache and remove old files
        script: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/

      - name: Install Homebrew and Node.js
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true
          brew install node

      - name: Install TypeScript
        script: |
          npm install -D typescript

      - name: Install Capacitor and Android platform
        script: |
          npm install @capacitor/cli @capacitor/android

      - name: Install OpenJDK 21 and Setup Environment (FORCE BREW PATH)
        script: |
          brew install openjdk@21 || brew reinstall openjdk@21
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          sudo mkdir -p /Library/Java/JavaVirtualMachines
          sudo rm -rf /Library/Java/JavaVirtualMachines/openjdk-21.jdk
          sudo ln -sfn "$JAVA_HOME" /Library/Java/JavaVirtualMachines/openjdk-21.jdk
          java -version
          javac -version
          echo "JAVA_HOME: $JAVA_HOME"

      - name: Install dependencies
        script: |
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          npm install

      - name: Check npm and npx version
        script: |
          npm --version
          npx --version

      - name: Check Gradle Version and JAVA_HOME
        script: |
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          javac -version
          gradle -v

      - name: Build project
        script: |
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          npm run build

      - name: Sync Capacitor with Android
        script: |
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          npx cap add android || true
          npx cap copy android
          npx cap sync android

      - name: Build APK
        script: |
          export JAVA_HOME="/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
          export PATH="$JAVA_HOME/bin:$PATH"
          echo "=== USING JDK 21 ==="
          java -version
          javac -version
          echo "JAVA_HOME: $JAVA_HOME"
          echo "===================="
          cd android
          ./gradlew clean assembleDebug --no-daemon --stacktrace

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
