workflows:
  android:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      # 可选：设置环境变量（部分脚本仍需手动 export）
      vars:
        JAVA_HOME: "/usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home"
    scripts:
      - name: Clean Gradle cache and remove old files
        script: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/

      - name: Install Homebrew and Node.js
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install node

      - name: Install TypeScript
        script: |
          npm install -D typescript

      - name: Install Capacitor and Android platform
        script: |
          npm install @capacitor/cli @capacitor/android

      - name: Install OpenJDK 21 (Required for Java 21 source)
        script: |
          brew install openjdk@21
          export JAVA_HOME=$(brew --prefix openjdk@21)/libexec/openjdk.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"

      - name: Install dependencies
        script: |
          npm install

      - name: Check npm and npx version
        script: |
          npm --version
          npx --version

      - name: Check Gradle Version and JAVA_HOME
        script: |
          export JAVA_HOME=$(brew --prefix openjdk@21)/libexec/openjdk.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          gradle -v
          echo "JAVA_HOME is set to: $JAVA_HOME"

      - name: Build project
        script: |
          npm run build

      - name: Sync Capacitor with Android
        script: |
          npx cap add android || true  # 忽略已存在
          npx cap copy android
          npx cap sync android

      - name: Build APK
        script: |
          # 再次确保 JAVA_HOME 正确（关键！）
          export JAVA_HOME=$(brew --prefix openjdk@21)/libexec/openjdk.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          cd android
          ./gradlew clean assembleDebug --no-daemon

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
