
workflows:
  android:
    name: Build Android APK
    instance_type: macos-latest
    platform: android
    sdk: android-29
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build project
        script: |
          npm run build
      - name: Sync Capacitor with Android
        script: |
          npx cap add android
          npx cap copy android
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
