workflows:
  default:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build
      - run:
          name: Install Capacitor dependencies
          command: npm install @capacitor/core @capacitor/cli
      - run:
          name: Synchronize Capacitor with Android
          command: npx cap copy android
      - run:
          name: Build APK
          command: |
            cd android
            ./gradlew assembleRelease
      - deploy:
          name: Deploy APK
          options:
            file: android/app/build/outputs/apk/release/app-release.apk
