workflows:
  default:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
    steps:
      # 1. Checkout the code
      - checkout

      # 2. Install dependencies
      - run:
          name: Install dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm install
            cd android && ./gradlew clean

      # 3. Build APK
      - run:
          name: Build APK
          command: |
            cd android && ./gradlew assembleRelease

      # 4. Deploy APK
      - deploy:
          name: Deploy APK
          options:
            file: "android/app/build/outputs/apk/release/app-release.apk"
