workflows:
  android:
    name: Build Android APK
    instance_type: mac_mini_m1  # 使用 Codemagic 支持的实例类型
    scripts:
      - name: Install Homebrew and Node.js
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install node
      - name: Install TypeScript
        script: |
          npm install -D typescript
      - name: Install Capacitor and Android platform
        script: |
          npm install @capacitor/cli @capacitor/android
      - name: Install OpenJDK 17 (Required for Gradle)
        script: |
          brew install openjdk@17
          export JAVA_HOME=$(brew --prefix openjdk@17)/libexec/openjdk.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Install dependencies
        script: |
          npm install
      - name: Check npm and npx version
        script: |
          npm --version
          npx --version
      - name: Build project
        script: |
          npm run build
      - name: Sync Capacitor with Android
        script: |
          npx cap add android
          npx cap copy android
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
