workflows:
  default:
    name: Build React Native + Capacitor Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
      node: latest
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Checkout
        script: |
          git checkout .
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli
      - name: Add Android platform
        script: |
          npx cap add android
      - name: Copy web assets to Android
        script: |
          npx cap copy android
      - name: Build APK (Release)
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - dev@yourcompany.com
        notify:
          success: true
          failure: true
