workflows:
  default:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
    steps:
      # 1. Checkout the code
      - checkout

      # 2. Install Flutter
      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git /opt/flutter
            export PATH="$PATH:/opt/flutter/bin"
            flutter doctor
            flutter pub get

      # 3. Build APK
      - run:
          name: Build APK
          command: |
            flutter build apk --release

      # 4. Deploy APK
      - deploy:
          name: Deploy APK
          options:
            file: build/app/outputs/flutter-apk/app-release.apk
