workflows:
  default:
    name: Build React + Capacitor Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        ANDROID_KEYSTORE_PATH: "$CM_KEYSTORE_PATH"
        ANDROID_KEYSTORE_PASSWORD: "$CM_KEYSTORE_PASSWORD"
        ANDROID_KEY_ALIAS: "$CM_KEY_ALIAS"
        ANDROID_KEY_PASSWORD: "$CM_KEY_PASSWORD"
        APP_ID: "com.yourcompany.yourapp"   # 替换为你的 App ID
        APP_NAME: "Your App Name"           # 替换为你的应用名
      node: latest
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Checkout
        script: |
          git checkout .
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor
        script: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
      - name: Initialize Capacitor (if config missing)
        script: |
          if [ ! -f capacitor.config.json ] && [ ! -f capacitor.config.ts ]; then
            npx cap init "$APP_NAME" "$APP_ID"
          fi
      - name: Add Android platform
        script: |
          npx cap add android
      - name: Copy web assets to Android
        script: |
          npx cap copy android
      - name: Build APK (Release)
        script: |
          cd android
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - dev@yourcompany.com
        notify:
          success: true
          failure: true
